controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0

    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2     # Allow slight lateral movement errorsss
      movement_time_allowance: 20.0      # Allow up to 20 seconds without progress

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      min_turning_radius: 0.55            # Your robot's minimum turning radius (55 cm)
      desired_linear_vel: 0.7s             # Preferred linear speed
      max_linear_vel: 1.2
      min_x_velocity_threshold: 0.5
      min_theta_velocity_threshold: 0.9
      lookahead_time: 2.5
      min_lookahead_dist: 1.0
      max_lookahead_dist: 2.5
      regulate_linear_velocity: true
      use_velocity_scaled_lookahead: true
      use_intermediate_goal: true
      allow_reversing: false
      rotate_to_heading_angular_vel: 1.2
      rotate_to_heading_min_angle: 3.14   # Disable rotate in place
      transform_tolerance: 0.1

