amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    laser_model_type: "likelihood_field"
    min_particles: 100
    max_particles: 5000
    resample_interval: 1
    update_min_d: 0.2
    update_min_a: 0.2
    transform_tolerance: 1.0
    set_initial_pose: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/ashish/map_lab.yaml"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.8
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      use_velocity_scaled_lookahead: true
      min_turning_radius: 0.2
      desired_linear_vel: 0.6
      max_linear_vel: 1.0
      max_lookahead_dist: 1.0
      min_lookahead_dist: 0.4
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.9
      rotate_to_heading_min_angle: 3.14  # disables rotate-in-place
      transform_tolerance: 0.1
      regulate_linear_velocity: true
      use_intermediate_goal: true
      allow_reversing: false

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.3
      footprint: "[[-0.2, -0.15], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.15]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 2.0
      publish_frequency: 2.0
      resolution: 0.05
      robot_radius: 0.3
      footprint: "[[-0.2, -0.15], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.15]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"

recoveries_server:
  ros__parameters:
    use_sim_time: false
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: false
    loop_rate: 20
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0

