amcl:
  ros__parameters:
    use_sim_time: false
    laser_min_range: 0.0
    laser_max_range: 12.0
    min_particles: 100
    max_particles: 5000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    motion_model_type: "diff-corrected"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_lambda_short: 0.1
    laser_model_type: "likelihood_field"
    set_initial_pose: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/ashish/ros2_ws/src/nav2_custom_launch/maps/map_home.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false
