# params_amcl.yaml

amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"          
    odom_frame_id: "odom"                
    map_frame_id: "map"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 5000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    laser_min_range: 0.0
    laser_max_range: 12.0
    laser_model_type: "likelihood_field"
    set_initial_pose: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/ashish/maps/my_map.yaml"   

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      use_velocity_scaled_lookahead_dist: true

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "odom"

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: true
    loop_rate: 20

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: true
    feedback: "OPEN_LOOP"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: "map"
      robot_base_frame: "base_link"
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.25
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      resolution: 0.05
      robot_radius: 0.25
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - amcl
      - controller_server
      - planner_server
      - bt_navigator
      - waypoint_follower
      - smoother_server
      - velocity_smoother

